### ISSUE TITLE
Use working directory instead of executable directory

### ISSUE THREAD

**Issue by aveao** [oct2pus/gomoji#2]
on https://github.com/oct2pus/gomoji/blob/master/main.go#L35, wouldn't it make more sense to use the working directory?

from what I can see online, you can access it with a code like this: https://gist.github.com/arxdsilva/4f73d6b89c9eac93d4ac887521121120

**Comment by oct2pus** [comment]
it does and its significantly less ugly in the code as well. Wish I noticed this sooner.
